const QUERY_KEY = {
  REGISTER: "REGISTER",
  USER: {
    DATA: "GET_USER_DATA",
    COUNT: "GET_USER_COUNT",
    IDS: "GET_USER_IDS",
  },
  FINGERPRINT: {
    DATA: "GET_FINGERPRINT_DATA",
    COUNT: "GET_FINGERPRINT_COUNT",
    IDS: "GET_FINGERPRINT_IDS",
  },
  ATTENDANCE: {
    DATA: "GET_ATTENDANCE_DATA",
    COUNT: "GET_ATTENDANCE_COUNT",
    IDS: "GET_ATTENDANCE_IDS",
  },
};

export default QUERY_KEY;
